apiVersion: v1
kind: Pod
metadata:
   name: ubuntu1
spec:
   restartPolicy: Never #Always OnFailure
   terminationGracePeriodSeconds: 1
   containers:
   - name: ubuntu
     image: ubuntu
     args:
     - "sleep"
     - "3000"