---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - handlers

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
