apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgresql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sudhauid"
        - name: POSTGRES_PASSWORD
          value: "sudhapwd"
        - name: POSTGRES_DB
          value: "sudhadb"
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-persistent-storage
        emptyDir: {}
