apiVersion: v1
kind: Pod
metadata:
  name: demo1 #name of the pod
  namespace: dev
  labels:
    name: demoapp1
spec:
  containers:
  - name: myapp #name of the container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "200m"
    ports:
      - containerPort: 80