apiVersion: v1
kind: Pod
metadata:
   name: multi-cloud
   namespace: jsns
spec:
   containers:
   - name: nginx
     image: nginx
     ports :
     - containerPort: 80
   - name: alpine
     image: alpine
     command: ['sh', '-c', 'sleep 60']


# output : 
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  37s   default-scheduler  Successfully assigned jsns/multi-cloud to node1
  Normal  Pulling    36s   kubelet            Pulling image "nginx"
  Normal  Pulled     31s   kubelet            Successfully pulled image "nginx" in 5.364s (5.364s including waiting)
  Normal  Created    30s   kubelet            Created container nginx
  Normal  Started    30s   kubelet            Started container nginx
  Normal  Pulling    30s   kubelet            Pulling image "alpine"
  Normal  Pulled     29s   kubelet            Successfully pulled image "alpine" in 1.32s (1.32s including waiting)
  Normal  Created    29s   kubelet            Created container alpine
  Normal  Started    29s   kubelet            Started container alpine
root@master:~/kubernets#

