apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc #name of the controller
  namespace: dev
  labels: #veriy imp. will use in service,
    type: dev
    app: nginx
    myapp: mynginx
spec:
  replicas: 2 #replicationController, ReplicaSet and deployment 
  # nodeName : minikube-m04 #Here we can give name of the node where the pod needs to be create. 
  selector:
    app: nginx #works on the labels
  template: #below details are belongs to Pod
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
  labels:
    type: service
    app: nginx
spec:
  type: ClusterIP #NodePorts, Loadbalancer
  selector: #labels of above file will be given here
    app: nginx
    type: dev
  ports:
  - port: 80
    targetPort: 80
