apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  namespace: jsmyns
  labels:
    app: nginx
spec:
  containers:
  - name: mynginx-container
    image: nginx
    resources:
      requests:
        memory: 3Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 500m
    ports:
    - containerPort: 80
