#js 
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pod-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pod-volume
    persistentVolumeClaim:
      claimName: mypvc