# js 

1. docker file : 

1. Create below file on the linux : 

root@wnode2:~/dockerdemo/first# docker build .
[+] Building 13.0s (9/9) FINISHED                                                                               docker:default
 => [internal] load build definition from Dockerfile                                                                      0.1s
 => => transferring dockerfile: 158B                                                                                      0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                          0.7s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [1/4] FROM docker.io/library/ubuntu:latest@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30    2.8s
 => => resolve docker.io/library/ubuntu:latest@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30    0.0s
 => => sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30 1.13kB / 1.13kB                            0.0s
 => => sha256:c920ba4cfca05503764b785c16b76d43c83a6df8d1ab107e7e6610000d94315c 424B / 424B                                0.0s
 => => sha256:35a88802559dd2077e584394471ddaa1a2c5bfd16893b829ea57619301eb3908 2.30kB / 2.30kB                            0.0s
 => => sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809 29.71MB / 29.71MB                          0.6s
 => => extracting sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809                                 1.9s
 => [internal] load build context                                                                                         0.0s
 => => transferring context: 66B                                                                                          0.0s
 => [2/4] RUN apt-get update                                                                                              4.2s
 => [3/4] RUN apt-get install -y nginx                                                                                    4.7s
 => [4/4] COPY index.js.html /var/www/html/                                                                               0.1s
 => exporting to image                                                                                                    0.4s
 => => exporting layers                                                                                                   0.3s
 => => writing image sha256:62e50731c26a3f939183211f9534737e5367791d1c7578b532ce8a9370bebe4f                              0.0s
root@wnode2:~/dockerdemo/first#

output : 

root@wnode2:~# curl 127.0.0.1:8000
js hello
root@wnode2:~#




root@wnode2:~/dockerdemo/first# ls -l
total 8
-rw-r--r-- 1 root root 131 Jun 20 05:45 Dockerfile
-rw-r--r-- 1 root root  26 Jun 20 05:12 index.nginx-debian.html
root@wnode2:~/dockerdemo/first# cat Dockerfile
FROM ubuntu
RUN apt-get update
RUN apt-get install -y nginx
COPY index.nginx-debian.html /var/www/html/
CMD nginx -g 'daemon off;'
root@wnode2:~/dockerdemo/first# cat index.nginx-debian.html
JS Welcome to docker file
root@wnode2:~/dockerdemo/first# pwd
/root/dockerdemo/first
root@wnode2:~/dockerdemo/first#


Docker file : 

FROM ubuntu
RUN apt-get update
RUN apt-get install -y nginx
COPY index.nginx-debian.html /var/www/html
CMD nginx -g 'daemon off;'




