- name: Just ping and print
  hosts: localhost
  connection: local
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world


- name: Example ansible playbook
  hosts: all
  # become: true
  tasks:
     - name: Creates directory structure
       ansible.builtin.file:
          path: ~/ansible-practice/day/jai-test
          #   path: /tmp/jai-test5
          state: directory
          mode: '0755'

#----------------------> cratafl.yml

- name: Create a file under tmp
  hosts: all
  tasks:
     - name: Create a file
       file:
          path: /tmp/jssudha.txt
          state: touch


- name: del dir
  become: true
  hosts: all
  tasks:
     - name: Del dir
       file:
          path: /tmp/js
          state: absent
          #recurse: yes


---
- name: Install Nginx
  hosts: all
  become: yes 

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

---
- name: UnInstall Nginx
  hosts: all
  become: yes 

  tasks:
    - name: UnInstall Nginx
      apt:
        name: nginx
        state: absent

    - name: Remove Nginx configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx
        - /var/log/nginx
        - /var/cache/nginx
        - /var/www/html


- name: Install Apache
  hosts: apacheservers
  become: true
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes


---
- name: Installing java on Node1
  hosts: sudha #node1
  become_user: root
    #become: yes
  tasks:
      - name: Installing java on my server
        apt:
          name: openjdk-11-jdk
          update-cache: true


- name: Installing mysql on Node2
  hosts: sudha
  become_user: root
  tasks:
      - name: Installing MYSQL on Node2
        apt:
            name: mysql-server
            update-cache: true

#----------------------------------------------------------------------------------------------------------------
- name: Installing Java and mysql
  hosts: all
  become_user: root
  tasks:
      - name: Installing java on my server
        hosts: java 
        apt:
           name: openjdk-11-jdk
           update-cache: true

           
		  
	  - name: Installing mysql on my server
	    hosts: mysql
      apt:
        name: mysql-server
        update-cache: true


#----------------------------------------------------------------------------------------------------------------

- name: Install Apache
  hosts: sudha
  become: true
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: latest
    notify:
      - restart web service
  handlers:
  - name: restart web service
    service:
      name: apache2
      state: restarted
      enabled: yes



#------------------------------------------------------------------- : Using handlers


# sudhakar@vm-w-2:~/ansible/ansible-handlers$ cat playbook.yml
# for all hosts 
---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - handlers

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

# below one is to run on the local host. 

ubuntu@ip-172-31-88-43:~/ansible-handler$ cat playbook.yml
---
- name: Example Ansible playbook for Handlers
  hosts: localhost
  become: true
  remote_user: ubuntu
  roles:
    - handlers

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

ubuntu@ip-172-31-88-43:~/ansible-handler$

# main program. 

sudhakar@vm-w-2:~/ansible/ansible-handlers/roles/handlers/tasks$ cat main.yml
---
- name: Update apt cache and install Nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
- name: Copy index.html
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.nginx-debian.html
    mode: u=rwx,go=r
- name: Copy updated.html
  ansible.builtin.template:
    src: updated.html
    dest: /var/www/html/index.nginx-debian.html
    mode: u=rwx,go=r
  notify:
    - Restart Nginx
sudhakar@vm-w-2:~/ansible/ansible-handlers/roles/handlers/tasks$

# How to test - name: 
1. check the OUTPUT via browser. 
2. update the updated file. 
3. re run the ansible program. 
4. refresh the page.. 



#-------------------------------------------------------------------

