# Install mysql on Linux
# Step 1 : Install mysql
#
#
#
#
#
#
#
#

# sudo apt-get remove --purge mysql-server mysql-client mysql-common
# sudo apt-get autoremove
# sudo apt-get autoclean
# sudo rm -rf /etc/mysql /var/lib/mysql

#[gatewayed]
#staging1 ansible_host=10.0.2.1
#staging2 ansible_host=10.0.2.2
https://www.liquidweb.com/kb/create-a-mysql-database-on-linux-via-command-line/

pip install MySQL-python
pip install pymysql

pwd of the "root" user is "rootroot"

---
- name: Install and configure MySQL
  hosts: localhost
  become: yes
  vars:
    mysql_root_password: ""
    mysql_user: "jssudha"
    mysql_user_password: "jssudhapwd"
    mysql_database: "mysqldb1"

  tasks:
    - name: Step1 - Install MySQL server package
      package:
        name: mysql-server
        state: present
      become: yes

    - name: Step2 - Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present
      become: yes