---
- name: Update apt cache and install Nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true

- name: Copy index.html
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.nginx-debian.html
    mode: u=rwx,go=r

## Update the content on the website
- name: Copy updated.html
  ansible.builtin.template:
    src: updated.html
    dest: /var/www/html/index.nginx-debian.html
    mode: u=rwx,go=r
  notify:
    - Restart Nginx
