# with Container and Node ports : 
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  extraPortMapping:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
- role: worker
- role: worker



#kind create cluster --config 01-cluster.yaml
#kind delete cluster
#kind create cluster --config  master2_node.yml