# Prometheus alerting and monitoring. 
Auther - Sean Bradley
--> Below url has all related links
https://sbcode.net/prometheus/delete-timeseries/

----------------------------------------------------------------------------------------------------------------------------
1. Installations. 
https://sbcode.net/prometheus/install-prometheus/

a. apt update 
b. apt install prometheus
c. Version : 
root@ip-172-31-88-43:~# prometheus  --version
prometheus, version 2.31.2+ds1 (branch: debian/sid, revision: 2.31.2+ds1-1ubuntu1.22.04.2)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20230502-12:17:56
  go version:       go1.18.1
  platform:         linux/amd64
root@ip-172-31-88-43:~#

User will be created : 

root@ip-172-31-88-43:~# cat /etc/passwd | grep -i prom
prometheus:x:115:122:Prometheus daemon,,,:/var/lib/prometheus:/usr/sbin/nologin
root@ip-172-31-88-43:~#


d. systemctl status prometheus
e. systemctl prometheus-node-exporter status
f. 
root@ip-172-31-88-43:~# ps -ef | grep prometheus
prometh+    1796       1  0 16:44 ?        00:00:00 /usr/bin/prometheus-node-exporter
prometh+    2274       1  0 16:45 ?        00:00:00 /usr/bin/prometheus
root        3083     791  0 16:48 pts/1    00:00:00 grep --color=auto prometheus
root@ip-172-31-88-43:~#
g. 9090 is the port. Enabled in bound rule AWS. 
http://54.158.158.88:9090/classic/graph
h. 9100 
http://54.158.158.88:9100
i. 

----------------------------------------------------------------------------------------------------------------------------

2. Domain update  : update the file and refresh it. 

root@ip-172-31-88-43:/etc/nginx/sites-enabled# vi prometheus

root@ip-172-31-88-43:/etc/nginx/sites-enabled# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

root@ip-172-31-88-43:/etc/nginx/sites-enabled# ls -l
total 4
lrwxrwxrwx 1 root root  34 Apr  2 21:08 default -> /etc/nginx/sites-available/default
-rw-r--r-- 1 root root 190 Apr  4 18:03 prometheus
root@ip-172-31-88-43:/etc/nginx/sites-enabled#

----------------------------------------------------------------------------------------------------------------------------
3. Traverse 9090 - url . 
a. Graph 
b. Status -> Targets. 

curl http://ip-172-31-88-43:9090/metrics 

c. graph -> process_cpu_seconds_total -> check the graph for 2 /3 or 6 hours 
d. status -> Check all options under this url. 
config.file 	/etc/prometheus/prometheus.yml


----------------------------------------------------------------------------------------------------------------------------
Install - prometheus node explorer on another Ubuntu server. 

sudo apt update
sudo apt install prometheus-node-exporter

sudo service prometheus-node-exporter status

Now, we need to add second node details at the first node config file. 

sudo nano /etc/prometheus/prometheus.yml --> here. 
add below line. 
    - targets: ['other-server-ip-or-domain:9100']

--> File was updated . 
root@ip-172-31-88-43:/etc/prometheus# diff prometheus.yml bkprometheus.yml
39d38
<       - targets: ['3.80.75.50:9100']
root@ip-172-31-88-43:/etc/prometheus# pwd
/etc/prometheus
root@ip-172-31-88-43:/etc/prometheus#

--> check : validate it. 
promtool check config /etc/prometheus/prometheus.yml


root@ip-172-31-88-43:/etc/prometheus# promtool check config /etc/prometheus/prometheus.yml
Checking /etc/prometheus/prometheus.yml
  SUCCESS: 0 rule files found

root@ip-172-31-88-43:/etc/prometheus# ls -l /etc/prometheus/prometheus.yml
-rw-r--r-- 1 root root 1466 Apr  4 19:45 /etc/prometheus/prometheus.yml
root@ip-172-31-88-43:/etc/prometheus#


sudo service prometheus restart
sudo service prometheus status

Validate : open 9090 url of the first node 
status -> targets 
There, we can see the new node details under the endpoint. 


---------------------------------------------------------------------------------------------------------------------------- 0405 - HitachiSreTraining
8. Deleting time series data . 
graph -> go_threads -> (there you can see couple of entries.)

You need to enable the admin API in Prometheus before you can.
sudo nano /etc/default/prometheus
Add --web.enable-admin-api to the ARGS="" variable. E.g.,
ARGS="--web.enable-admin-api"

sudo service prometheus restart
sudo service prometheus status

Beofre : 
status -> command-line flags -> web.enable-admin-api 	false
--> set above line (ARGS) at prometheus file and restart the service. 
then web.enable-admin-api becomes true. 

Run below command : 
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={instance="sbcode.net:9100"}'
--> Here we need to give the exact one (need to copy from the graph (go_threads) instead of sbcode.net:9100.. 




----------------------------------------------------------------------------------------------------------------------------
9. promoql : 
scrape_duration_seconds --> give this at expressions. 
It gives 3 situations. = scrapes 
scrape_duration_seconds{job="node"}
scrape_duration_seconds{instance="3.80.75.50:9100"}
Above one will give only one entry. This way we can see the details of an entry . 
Now search for - 
a. node_cpu_seconds_total
b. node_cpu_seconds_total{mode=~".*irq"} ----------> for specific set. 
c. soft.* --> we can use any regular expression. 
d. scrape_duration_seconds{instance="localhost:9100"} 
e. scrape_duration_seconds{instance="localhost:9100"}[2m]
f. scrape_duration_seconds[5m] --> gives for all of the instances. 
g. 




----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
