apiVersion: v1
kind: Pod
metadata:
   name: ubuntu1
spec:
   restartPolicy: Never #Always OnFailure
   containers:
   - name: ubuntu
     image: ubuntu
     args:
     - "/bin/sh"
     - "-c"
     - "echo This is my path: $PATH"