apiVersion: v1
kind: Pod
metadata:
   name: jspod1
spec:
   terminationGracePeriodSeconds: 1
   containers:
   - name: nginx-1
     image: nginx
   - name: util
     image: vinsdocker/util 
     args:
     -   "sleep"
     -   "3600"    