#js 

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:
      httpGet:
        path: / #/home #/  - test with a wrong path
        port: 80
      periodSeconds: 10 #start of pod will be done in 1 sec
      failureThreshold: 3 #how many consecutive failures are allowed