#js 

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:
      exec:        
        command:
          - "cat"
          - "dummy.txt" # this file should exists else Pod will not start
      periodSeconds: 10 #start of pod will be done in 1 sec
      failureThreshold: 3 #how many consecutive failures are allowed