apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: my-rs-1
spec:
   selector:
      matchLabels:
         app: my-app-1
   replicas: 2
   template:
      metadata:
         labels:
            app: my-app-1
      spec:
         containers:
         - name: nginx
           image: nginx
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: my-rs-2
spec:
   selector:
      matchLabels:
         app: my-app-2
   replicas: 2
   template:
      metadata:
         labels:
            app: my-app-2
      spec:
         containers:
         - name: nginx
           image: nginx