apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: nginx
  spec:
    containers:
    -name: mynginx-container
      - image:  nginx
        resources:
          limits:
            memeory: "128Mi"
            cpu: "500m"

            

      name:  my-name
      env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE