#Deploymnet revisions
apiVersion: apps/v1
kind: Deployment
metadata:
   name: order-service-deploy
   annotations:
      kubernetes.io/
spec:
   selector:
      matchLabels:
         app: order-service
   replicas: 2
   template:
      metadata:
         labels:
            app: order-service
      spec:
         containers:
         - name: order-service
           image: vinsdocker/k8s-app:v3
           #check with v1, v2 and v3
           #check with command - kubectl rollout history deploy           
           ports:
           - name: "app-port"
             containerPort: 80