kind: Pod
apiVersion: v1
metadata:
  name: jsmypod
  namespace: jsns
  labels:
    app: jsmyapp
    env: dev
spec:
  containers:
    - name: cont1
      image: tomcat
      ports:
        - name: tomcatport
          containerPort: 8080