#init container

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: jsns
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: tomcat
    ports:
    - containerPort: 8080
  initContainers:
  - name: init-busybox
    image: busybox
    command: ['sh', '-c', 'sleep 60']
  - name: init-alpine
    image: alpine


# Events:
#   Type    Reason     Age   From               Message
#   ----    ------     ----  ----               -------
#   Normal  Scheduled  87s   default-scheduler  Successfully assigned jsns/myapp-pod to node2
#   Normal  Pulling    86s   kubelet            Pulling image "busybox"
#   Normal  Pulled     85s   kubelet            Successfully pulled image "busybox" in 1.403s (1.403s including waiting)
#   Normal  Created    85s   kubelet            Created container init-busybox
#   Normal  Started    85s   kubelet            Started container init-busybox
#   Normal  Pulling    24s   kubelet            Pulling image "alpine"
#   Normal  Pulled     23s   kubelet            Successfully pulled image "alpine" in 1.247s (1.247s including waiting)
#   Normal  Created    23s   kubelet            Created container init-alpine
#   Normal  Started    23s   kubelet            Started container init-alpine
#   Normal  Pulling    22s   kubelet            Pulling image "tomcat"
#   Normal  Pulled     6s    kubelet            Successfully pulled image "tomcat" in 15.723s (15.724s including waiting)
#   Normal  Created    6s    kubelet            Created container myapp-container
#   Normal  Started    6s    kubelet            Started container myapp-container
# root@master:~# kubectl get pods -n jsns
# NAME        READY   STATUS    RESTARTS   AGE
# myapp-pod   1/1     Running   0          90s
# root@master:~#
