kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrs
  namespace: jsns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

root@master:~/kubernets# kubectl get pods -n jsns | grep myrs
myrs-bh4vc    1/1     Running            0                2m31s
myrs-lm4p8    1/1     Running            0                2m31s
myrs-qncj2    1/1     Running            0                2m31s
root@master:~/kubernets#

root@master:~/kubernets# kubectl get pods -n jsns -o wide | grep myrs
myrs-bh4vc    1/1     Running            0                3m34s   192.168.104.12    node2   <none>           <none>
myrs-lm4p8    1/1     Running            0                3m34s   192.168.166.133   node1   <none>           <none>
myrs-qncj2    1/1     Running            0                3m34s   192.168.166.134   node1   <none>           <none>
root@master:~/kubernets#

root@master:~/kubernets# kubectl get replicaset -n jsns
NAME   DESIRED   CURRENT   READY   AGE
myrs   3         3         3       6m36s
root@master:~/kubernets#


